// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenaciendoWebAPI.Datos;

#nullable disable

namespace RenaciendoWebAPI.Migrations
{
    [DbContext(typeof(RenacerContext))]
    [Migration("20230414012033_datos")]
    partial class datos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RenaciendoWebAPI.Models.Renacer", b =>
                {
                    b.Property<int>("RenacerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenacerId"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenacerId");

                    b.ToTable("Renaceres");

                    b.HasData(
                        new
                        {
                            RenacerId = 1,
                            Amenidad = "Chiste de 🐈‍",
                            Detalle = "Siempre",
                            Dimension = 123,
                            FechaActualizacion = new DateTime(2023, 4, 13, 20, 20, 33, 101, DateTimeKind.Local).AddTicks(1787),
                            FechaCreacion = new DateTime(2023, 4, 13, 20, 20, 33, 101, DateTimeKind.Local).AddTicks(1776),
                            Nombre = "Manzanita"
                        },
                        new
                        {
                            RenacerId = 2,
                            Amenidad = "Chiste de 🍏",
                            Detalle = "Constante",
                            Dimension = 321,
                            FechaActualizacion = new DateTime(2023, 4, 13, 20, 20, 33, 101, DateTimeKind.Local).AddTicks(1790),
                            FechaCreacion = new DateTime(2023, 4, 13, 20, 20, 33, 101, DateTimeKind.Local).AddTicks(1789),
                            Nombre = "Mau"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
